name: Build Sarwar Translate APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Find Android SDK
        shell: bash
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          find "$ANDROID_HOME" -name sdkmanager -type f

      - name: Install Android SDK
        shell: bash
        run: |
          SDKMANAGER=$(find "$ANDROID_HOME/cmdline-tools" -name sdkmanager -type f | head -n 1)
          echo "Using: $SDKMANAGER"

          yes | "$SDKMANAGER" --licenses || true

          "$SDKMANAGER" \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Check Gradle
        run: |
          which gradle
          gradle --version

     - name: Show Gradle tasks
         run: gradle tasks

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Sarwar-Translate-APK
          path: app/build/outputs/apk/debug/app-debug.apk
